
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_observer_development
test: &test
  <<: *default
  database: ruby_observer_test

production:
  <<: *default
  database: ruby_observer_production
  username: ruby_observer
  password: <%= ENV['RAILS_DEMO_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
